feat: add a step to github actions, that fails if there was an error, after it has commited the changes (to allow partial saving the scraped data)

diff --git a/.github/workflows/eurcopscraper.yaml b/.github/workflows/eurcopscraper.yaml
--- a/.github/workflows/eurcopscraper.yaml
+++ b/.github/workflows/eurcopscraper.yaml
@@ -54,3 +54,10 @@ jobs:
           git add --all
           git commit -am "add data"
           git push 
+
+      - name: Check for failed.txt
+        run: |
+          if [ -f "logs/failed.txt" ]; then
+            echo "Error: logs/failed.txt exists, indicating a previous failure."
+            exit 1
+          fi
